version: "3.9"  # Frissítve egy újabb verzióra

services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Hugzi_139_112
      - DATABASE_NAME=fastapi_sm
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Hugzi_139_112
      - POSTGRES_DB=fastapi_sm
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
